### ISSUE TITLE
How to import math module

### ISSUE THREAD

**Issue by jessiejc23** [JasonLiJT/Gravitational-Python-Keyboard#1]
Hi @JasonLiJT does it work if you use import math instead of from math import *?

**Comment by JasonLiJT** [comment]
**Yes, it works.** @jessiejc23 

However, you'll need to type five more characters `math.` to use the library (e.g. `math.pi` instead of `pi`), which decreases the coding speed significantly.

You can see **_the typing speed, instead of the code style, is the major limitation_**: www.youtube.com/watch?v=kBGhWRW39Zo

After all, the codes are not written to be read. On the micro:bit chip, you just type as few characters as possible to run the expected codes so it's unnecessary to keep good coding style or make comments.
